name: CI - Run checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # checks all of the versions allowed in pyproject.toml
        python-version: ["3.11", "3.12"]

    steps:
      # installs python
      # one execution of the tests per version listed above
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # install poetry
      - uses: Gr1N/setup-poetry@v8

      - name: Install package using poetry
        run: make install

      - name: Run linting
        run: make lint

      - name: Run tests
        run: make test-audit
